### ISSUE TITLE
Upgrade to GOV.UK Design System version 3.6.0

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/govuk_design_system_formbuilder#100]
Version 3.6.0 of the frontend has been released. Based on the [release notes](https://github.com/alphagov/govuk-frontend/releases/tag/v3.6.0) it doesn't look like the form builder needs any new behaviour.

One area that _might_ need addressing is that now the guidance now specifies that number inputs should use `inputmode` and `pattern` instead of `type="number"`. However, that can already be achieved using the `govuk_text_field` and supplying the extra params manually.

Open to suggestion on this, but for the time being I think I'll leave it as is.

**Comment by tvararu** [comment]
I think that's reasonable; maybe some guidance on the text field page with an example would suffice? https://govuk-form-builder.netlify.com/form-elements/text-field/
