### ISSUE TITLE
When injecting content, error message position is wrong 

### ISSUE THREAD

**Issue by zheileman** [DFE-Digital/govuk_design_system_formbuilder#102]
Example with right position of error message:

<img width="675" alt="Screen Shot 2020-03-26 at 15 45 24" src="https://user-images.githubusercontent.com/687910/77666415-d5167980-6f78-11ea-94cb-d2cabb68ede1.png">

Example using the gem and an injected paragraph:

<img width="680" alt="Screen Shot 2020-03-26 at 15 45 59" src="https://user-images.githubusercontent.com/687910/77666489-ecedfd80-6f78-11ea-90f0-ae5066422f56.png">

The workaround at the moment is, in these cases, to not use the fieldset legend to include the header, but instead to render the header (and any content in between this and the radios) separately, and then set the legend to visually hidden.

Or, in this case in particular, to change the little paragraph to hint text. But in other scenarios, this might not work out well. Example:

<img width="677" alt="Screen Shot 2020-03-26 at 15 51 42" src="https://user-images.githubusercontent.com/687910/77667121-b5338580-6f79-11ea-85b8-38843c1ef7fb.png">

**Comment by peteryates** [comment]
Hey @zheileman, I _think_ I've fixed this in #103. If you're using the `#govuk_radio_buttons_fieldset`/`#govuk_check_boxes_fieldset` varients this is slightly more complicated and might necessitate adding a new helper to the builder so users can place them exactly where they want them.

However, for the described problem above I believe my fix will suit your needs for the time being. Please let me know and I'll get a release out today.

**Comment by zheileman** [comment]
Hi @peteryates, thank you very much. Yes this solves the mentioned issue. I've not gone too far with the gem, I've just started using it for a legacy project (built with form elements) that we intend to migrate to the new design system.

We don't need this fix released any time soon, so feel free to accommodate this change any way you see fit 👍
