### ISSUE TITLE
Revealing content with inline radios alignment glitch

### ISSUE THREAD

**Issue by zheileman** [DFE-Digital/govuk_design_system_formbuilder#104]
Hello,

Not really sure if this is something we are doing wrong but when trying to reveal content (in this case a text area) linked to an inline radio button, the alignment looks odd.

Example (nothing selected):

<img width="730" alt="Screen Shot 2020-03-30 at 12 22 01" src="https://user-images.githubusercontent.com/687910/77907387-73f4eb80-7281-11ea-8862-e11341202df1.png">

Example, YES option selected (this is the option revealing the text area):

<img width="697" alt="Screen Shot 2020-03-30 at 12 25 14" src="https://user-images.githubusercontent.com/687910/77907446-8e2ec980-7281-11ea-8c84-3613f29dd812.png">

How we think it should look (please note this screenshot is when using the "old" [elements form builder](https://github.com/ministryofjustice/govuk_elements_form_builder)):

<img width="662" alt="Screen Shot 2020-03-30 at 12 28 04" src="https://user-images.githubusercontent.com/687910/77907684-efef3380-7281-11ea-859d-e543b92a8f58.png">

Perhaps this is a limitation of the expected new design system markup, and maybe we can't use inline radios if there is revealing content, although it would be great if possible, as it is very common to have "yes-no" questions with normally the Yes revealing a text box or text area for more details, and inline looks more pleasant in these cases.

Please let me know if you need more details. Again, this is not urgent, we are starting to use the gem and we might find some limitations we might need to workaround.

Thank you!

**Comment by aliuk2012** [comment]
Hi @zheileman 

TBH, I've never seen inline radio buttons with revealing content. The main reason for this is that if you are designing a progressively enhanced service, how would users know whether `Provide details` is for `Yes` or `No`? At least if JavaScript is turned off or fails to load for whatever reason then the user would still understand how the textarea is related to the answer because it would be positioned directly under each option.

I'd suggest reviewing the designs and possibly making your radio buttons not inline.

**Comment by zheileman** [comment]
Hey @aliuk2012 thanks for your response.

Yes you are right, without javascript (admittedly less and less common) it might pose some confusion as the revealing element would then not be positioned next to the radio that "control" this revealing element.

We've been using inline radios with revealing text areas quite a lot in one of our services, with no issues so far, although we realised what you are saying.

Also at the same time we've found the fact that stacked revealing radios "move" around the radios off the screen quite annoying and not so pleasant to users. In this particular example, if the radios are stacked, when selecting Yes the text area is revealed pushing the No radio down, sometimes off the screen if you are on mobile.
But I imagine this has been discussed previously and found to be a non-issue for most users.

We will think what to do, probably as you mention, revert to stacked radios when we are revealing elements (even if it is just 2 radios like in this case, as for more than 2 radios we always used the stacked regardless).

Thank you again!

**Comment by aliuk2012** [comment]
> Also at the same time we've found the fact that stacked revealing radios "move" around the radios off the screen quite annoying and not so pleasant to users. In this particular example, if the radios are stacked, when selecting Yes the text area is revealed pushing the No radio down, sometimes off the screen if you are on mobile.

Good point but I think it depends on how much additional content is being shown/hidden as to how much of a problem this is. If you are showing a lot of additional fields or content then it might be a better option to place that on another new page that is conditionally branched to based on the radio button option selected.

**Comment by peteryates** [comment]
> Perhaps this is a limitation of the expected new design system markup, and maybe we can't use inline radios if there is revealing content

It is my understanding that this is the intention of the design system. As @aliuk2012 says, without JavaScript it wouldn't be apparent to which radio button the text area _belonged_. As this gem doesn't come with any CSS, adding this functionality would be quite an involved task.

I'm going to close this for the time being. If the pattern ever makes it into the design system it will be fully supported.
