### ISSUE TITLE
Support captions or custom html in page headings.

### ISSUE THREAD

**Issue by aliuk2012** [DFE-Digital/govuk_design_system_formbuilder#133]
## Background
In our service we have alot of pages which use a heading caption to give the user a better idea of which training provider they are actioning on behalf of. See GOV.UK Design System examples https://design-system.service.gov.uk/styles/typography/#headings-with-captions

## Issues
Currently inputs/radios and I suspect checkboxes do no support captions or custom html inside the legend/label text. What also raises a concern is that the caption may or may not be considered part of the page heading. If it is considered as part of the heading then the span should sit inside the heading element.

If you were to consider error styling then it should also include the caption within the error group
eg:
![image](https://user-images.githubusercontent.com/3441519/83065073-c1f85680-a05a-11ea-8fe8-9d8763e4995c.png)

## Example of usage in our service
- [radio button fieldset legend example](https://github.com/DFE-Digital/publish-teacher-training/blob/master/app/views/providers/allocations/new_repeat_request.html.erb#L10-L18)

- [Input label using h1](https://github.com/DFE-Digital/publish-teacher-training/blob/master/app/views/providers/allocations/number_of_places.html.erb#L18-L28)

**Comment by peteryates** [comment]
Good call, I'll add this to the `legend` and `label` options, probably in the following format:

```slim
= form.govuk_text_field(:number_of_places,
   label: {
   text: "How many places would you like to request?",
     size: "xl",
     tag: "h1",
     caption: @training_provider.provider_name
   },
   pattern: "[0-9]*",
   inputmode: "numeric",
   width: 10) do
```

**Comment by aliuk2012** [comment]
Is it worth adding a `caption_position` which would accept either `inside` or `outside` which would control the positioning of the caption?

**Comment by aliuk2012** [comment]
The caption could include visually hidden content for screenreader users too

**Comment by peteryates** [comment]
If it's meant to be outside wouldn't just manually placing the caption outside work?

```slim
span.govuk-caption = @training_provider.provider_name

= form.govuk_text_field(:number_of_places, ...)
```

With regards to visually hidden captions I'd be inclined to let them be configured manually (and left outside the helper) too. There's no reference to hiding them in the design system docs.

**Comment by aliuk2012** [comment]
I suppose placing the caption outside like I have already done would work, it just means that the page would look like the screenshot above with the caption not being included in the error form group.

I know the design system doesn't mention it but I've seen services where extra visually hidden content is included.


Eg. 
```
<span class="govuk-caption-xl">
  <span class="govuk-visually-hidden">You are currently viewing </span>
  <%= provider_name %>
</span>
```

Eg. 

```
<span class="govuk-caption-xl">
  <%= provider_name %><span class="govuk-visually-hidden">:</span>
</span>
<h1>Location</h1>
```

**Comment by peteryates** [comment]
> I suppose placing the caption outside like I have already done would work, it just means that the page would look like the screenshot above with the caption not being included in the error form group.

Ah, I see what you mean now, inside or outside the `tag`, not the `.form-group`. Makes sense.

I think this could be solved entirely by allowing legend to take a proc rather than a hash, similar to [how it works on `#govuk_collection_radio_buttons`](https://govuk-form-builder.netlify.app/form-elements/radios/#populating-values-labels-and-hints-with-procs). That would keep the API simple but allow full customisation of the contents of `<legend>`.

**Comment by aliuk2012** [comment]
That sounds a good approach 👍
