### ISSUE TITLE
Extraneous additional spaces in button class attribute (maybe others?)

### ISSUE THREAD

**Issue by zheileman** [DFE-Digital/govuk_design_system_formbuilder#146]
Hello,

After updating to the latest version, we've seen under certain circumstances some extraneous spaces added to the **govuk-button** input class, like this:

```
class="govuk-button     "    // (5 extra spaces)
```

Or this (when an additional class is provided):

```
class="govuk-button  govuk-button--secondary   "    // (2 and 3 extra spaces)
```

Note this is the "raw" output from the builder. When inspecting the rendered html markup, 2 or more spaces are collapsed into 1 space, so in both examples there will just be one extra space appended to the end of the class attribute.

We think this was introduced in the recent refactoring PR as, in particular for `Elements::Submit` (maybe others?) a `#compact` in a collection was removed.

It is not the end of the world but as we have some tests that expect the exact markup to be generated to detect regressions, this was surfaced.

**Comment by peteryates** [comment]
Thanks for highlighting this. I suspect a `.compact` was removed in the refactor. Will fix tomorrow and get a release out
