### ISSUE TITLE
Document the branding feature

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/govuk_design_system_formbuilder#162]
Branding, which was added in [`v1.2.0`](https://github.com/DFE-Digital/govuk_design_system_formbuilder/releases/tag/v1.2.0), originally had a documentation page in the guide (added in 379f42b15af6c) that detailed its use.

Branding was added specifically to support an NHS COVID19 project. Unfortunately, the [NHS Design System](https://service-manual.nhs.uk/design-system) (forked from GOV.UK) has changed the way JavaScript plugins are initialised and the following functionality doesn't work:
 * `#govuk_text_area` character and word counts
 * `#govuk_check_box` conditional content
 * `#govuk_radio_button` conditional content

It has recently come to my attention that there is also a [Slovakian fork](https://github.com/slovensko-digital/navody-frontend/) which appears to be _much closer_ to GOV.UK.

The branding feature should be publicised and the documentation improved. There's no reason not to share common tools.

* [x] Find out which forks exist, detail them here and see how far they've veered from the original (if at all)
* [ ] Check how well the form builder works with forks
* [ ] Add and update removed guide page (referenced above)
* [ ] Add checked versions to the guide, a list or table depending on how many there are
* [ ] Add the link to the branding guidance back to the guide homepage

**Comment by peteryates** [comment]
I noticed @jsuchal has starred this project - do you have any thoughts on this?

**Comment by peteryates** [comment]
Here's an [incomplete] list of design systems built in a similar vein to the GOV.UK one:

| Country / Agency | URL                                                                        | Compatible with GOV.UK? | Notes                                                                                                                                                                                                |
| -------          | ---                                                                        | ---------------------- | -----                                                                                                                                                                                                |
| UK               | https://design-system.service.gov.uk/                                      | -                      |                                                                                                                                                                                                      |
| NHS              | https://service-manual.nhs.uk/design-system                                | Almost                 | Incredibly similar to the GOV.UK one but JavaScript is triggered by a different set of classes/attributes. The main difference between the two is that the 'brand' prefix `nhsuk` instead of `govuk`
| Netherlands      | https://nl-design-system.gitlab.io/                                        | No                     |                                                                                                                                                                                                      |
| USA              | https://designsystem.digital.gov/                                          | No                     |                                                                                                                                                                                                      |
| Argentina        | https://argob.github.io/poncho/                                            | No                     |                                                                                                                                                                                                      |
| Slovakia         | https://frontend.navody.digital/                                           | Yes                    | Some parts are prefixed with `svk` but others remain `govuk`. Looks to be a WIP                                                                                                                              |
| Australia        | https://designsystem.gov.au/                                               | No                     | Heavily inspired by the GOV.UK design system but there are some major deviations in the markup
| Canada           | https://design.gccollab.ca                                                 | No                     |                                                                                                                                                                                                      |
| Italy            | https://italia.github.io/bootstrap-italia/docs/come-iniziare/introduzione/ | No                     | Based on Bootstrap                                                                                                                                                                                   |
| New Zealand      | https://design-system-alpha.digital.govt.nz/                               | No                     | Heavily inspired by the GOV.UK one but the markup is incompatible                                                                                                                                    |
| Singapore        | https://www.designsystem.gov.sg/                                           | No                     | Based on Bootstrap, visual similarities with GOV.UK design system                                                                                                                                    |
| Switzerland      | https://swiss.github.io/styleguide/en/                                     | No                     |                                                                                                                                                                                                      |
| Brazil           | http://dsgov.estaleiro.serpro.gov.br/                                      | No                     |                                                                                                                                                                                                      |
| France           | https://design.numerique.gouv.fr/                                          | No                     | Currently in progress, specification not yet published                                                                                                                                               |
| Scotland         | https://resources.mygov.scot/design-standards/                             | No                     | Currently in progress, specification not yet published                                                                                                                                               |

**Comment by peteryates** [comment]
It doesn't look like there are any design systems that are fully compatible that don't just mix and match prefixes. Going to close this for the moment as the behaviour's already covered in [the guide](https://www.rubydoc.info/gems/govuk_design_system_formbuilder/GOVUKDesignSystemFormBuilder).

**Comment by jsuchal** [comment]
Just a small correction: The official slovak fork is here https://github.com/id-sk/id-sk-frontend AFAIK the govuk prefix was left intact.
