### ISSUE TITLE
Unable to set label content

### ISSUE THREAD

**Issue by paulrobertlloyd** [DFE-Digital/govuk_design_system_formbuilder#177]
I’m trying to implement an address pattern using multiple text inputs, [as described in the design system](https://design-system.service.gov.uk/patterns/addresses/). This requires the following HTML:

```html
<div class="govuk-form-group">
  <label class="govuk-label" for="address-line-1">
    Building and street <span class="govuk-visually-hidden">line 1 of 2</span>
  </label>
  <input class="govuk-input" id="address-line-1" name="address-line-1" type="text" autocomplete="address-line1">
</div>
```

Looking through [the docs](https://govuk-form-builder.netlify.app/introduction/labels-captions-hints-and-legends/#setting-label-content-with-a-proc), I thought I could achieve this with the following:

```erb
<%= f.govuk_text_field :address_line1, autocomplete: 'address-line1', label: -> do %>
  Building and street <span class="govuk-visually-hidden">line 1 of 2</span>
<% end %>
```

However it appears that this replaces all the content of this helper, both the `label` and the text `input`, whereas the documentation suggests this should only replace the content of the `label` element. Am I misinterpreting the documentation, or is this a bug? /cc @tvararu

**Comment by tvararu** [comment]
Tested this locally, code:

![Screenshot 2020-08-14 at 12 21 46](https://user-images.githubusercontent.com/1650875/90244468-bed66080-de28-11ea-94ee-36503cbef2a0.png)

Result:

![Screenshot 2020-08-14 at 12 21 52](https://user-images.githubusercontent.com/1650875/90244481-c4cc4180-de28-11ea-9bd7-93e44cb61a6e.png)

**Comment by peteryates** [comment]
This happens because the `label` is expecting a [`Proc`](https://ruby-doc.org/core-2.7.1/Proc.html) instead of a block. We can't pass the label a block because `govuk_text_field` already accepts them for [supplementary content](https://govuk-form-builder.netlify.app/building-blocks/injecting-content/) and it would get extremely confusing.

The proc is expecting Ruby rather than ERB, but you can render whatever you like via `render` or calling a helper:

```slim
/_name_label.slim

| Building and street

span.govuk-visually-hidden
  | line 1 of 2
```

```slim
/_form.slim

= form_for @person do |f|

  = f.govuk_text_field :name, label: ->{ render partial: 'name_label' }
```

Alternatively, using a helper:

```ruby
module PeopleHelper
  def name_label
    safe_join(["Building and street", tag.span("line 1 of 2", class: 'govuk-visually-hidden')])
  end
end
```

Hope this helps.

In your example, passing `foo` in a block is indeed overwriting the entire element; it's a bug and was definitely unexpected. I'll raise a ticket. It should probably raise instead.

**Comment by paulrobertlloyd** [comment]
Thanks for info! Honestly, this is all gibberish to me (I make edits to our Ruby app purely by trail and error!), but the inline method works for me.

Might it be possible to add a similar example to the docs? We don’t use Slim templates, so the current examples are not helpful, and actually a little confusing.

**Comment by peteryates** [comment]
I'm going to close this and am continuing to explore adding ERB snippets in #118 

Unfortunately, and this was news to me, Rails' ERB isn't standard and using Rails' implementation outside of Rails (the guide is generated using [Nanoc](https://nanoc.ws/)) doesn't look like the most straightforward of tasks.

On the positive side, Slim only takes about five minutes to learn if you already know CSS selector syntax :joy:
