### ISSUE TITLE
When using a proc for custom legend HTML, no legend tag is included by default

### ISSUE THREAD

**Issue by fofr** [DFE-Digital/govuk_design_system_formbuilder#199]
https://govuk-form-builder.netlify.app/introduction/labels-captions-hints-and-legends/#fully-customising-legends-with-procs

![Screen Shot 2020-09-29 at 11 39 48](https://user-images.githubusercontent.com/319055/94548478-b0ad9980-0248-11eb-9ca2-91eaec522704.png)

Should the docs include a legend HTML tag here, or should the code be inserting one automatically?

**Comment by peteryates** [comment]
Ah, that's an omission from the docs; the proc is intended to allow the legend to be fully controlled. Thanks, I'll get that sorted.
