### ISSUE TITLE
govuk_submit shoudl output a button not an input type=submit

### ISSUE THREAD

**Issue by aliuk2012** [DFE-Digital/govuk_design_system_formbuilder#203]
@edwardhorsford raised a good point here https://github.com/DFE-Digital/register-trainee-teacher-data/pull/58#discussion_r496082292 that `form.govuk_submit` method should output a `<button>` instead of `<input type="submit"...>`. 

There is a benefit of using the button as you can also use html inside the button which could be set using a block. by default a button inside a form should submit the form by default

**Comment by peteryates** [comment]
As discussed in #207 this is probably better served with a component or directly in the template.
