### ISSUE TITLE
Page <title> tag

### ISSUE THREAD

**Issue by david-mears-dfe** [DFE-Digital/govuk_design_system_formbuilder#225]
This might well be out of scope for the formbuilder, but I notice that [GDS guidelines](https://design-system.service.gov.uk/patterns/validation/#how-to-tell-the-user-about-validation-errors) say of the validation pattern that we should

> add ‘Error: ’ to the beginning of the page <title> so screen readers read it out as soon as possible

Forms don't have much to do with page titles, but I don't really know how the GDS Formbuilder works its magic, so I am just asking on the off chance that it is possible that there is an efficiency saving here.

**Comment by peteryates** [comment]
I'd say that's out of the form builder's remit.

The [Claim additional payments](https://github.com/DFE-Digital/claim-additional-payments-for-teaching) team have a nice solution where [they prepend `Error:` to the page title](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/blob/master/app/helpers/application_helper.rb#L2) and then [set `show_errors` dynamically](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/blob/c796a3af7e7cc835bde2f2acdad21392bcd81e97/app/views/student_loans/claims/claim_school.html.erb#L1) on pages where they show forms.

Perhaps there's scope for doing this with `content_for` and doing something from within a form but I don't know how well that approach would work.

**Comment by peteryates** [comment]
I hope the above covers the topic for the time being. More than happy to discuss further or make amendments to ease the process of setting the title.
