### ISSUE TITLE
Include_hidden option in collection_check_boxes

### ISSUE THREAD

**Issue by njseeto** [DFE-Digital/govuk_design_system_formbuilder#238]
We would like to be able to pass `include_hidden: false` into a `govuk_collection_check_boxes`.
https://github.com/DFE-Digital/govuk_design_system_formbuilder/blob/master/lib/govuk_design_system_formbuilder/elements/check_boxes/collection.rb#L59

We tried to investigate the code, and we were unable to identify a way to pass this in. Are there any suggestions or is it possible to have this feature added?

I will cc my colleagues for transparency @brenetic @tomas-stefano

**Comment by peteryates** [comment]
The corresponding `#govuk_collection_radio_buttons` does so adding one that works in the same way should be straightforward, I'll have it in for the next release.

**Comment by brenetic** [comment]
awesome! thanks very much @peteryates

**Comment by peteryates** [comment]
No worries @brenetic, will aim for a release today.
