### ISSUE TITLE
Documentation: checkbox copy under wrong heading

### ISSUE THREAD

**Issue by ethanmills** [DFE-Digital/govuk_design_system_formbuilder#243]
It looks like the "small checkboxes" information from this line on should actually be under "Generating a single checkbox" https://github.com/DFE-Digital/govuk_design_system_formbuilder/blob/6bd77bbfb7a1b9e469ecb786f5f35d56a1e42a78/guide/content/form-elements/checkboxes.slim#L56

**Comment by peteryates** [comment]
Thank you for reporting this @ethanmills, I've moved the quote and attempted to make the phrasing in that section clearer.

**Comment by ethanmills** [comment]
Thanks for picking this up so quickly! I've added a comment on the PR
