### ISSUE TITLE
Error when attempting to render `govuk_date_field` with `nil` Date object values

### ISSUE THREAD

**Issue by cwrw** [DFE-Digital/govuk_design_system_formbuilder#259]
After upgrading to the latest version: `2.4.0`, when attempting to render a date field using `govuk_date_field` with `nil` Date object segment values the following error is thrown: 
```
IndexError:
  #   offset 3 too large for struct(size:3)
```
Whilst running this outside tests the form renders correctly as we have empty string values specified for the [segments](https://github.com/DFE-Digital/govuk_design_system_formbuilder/blob/master/lib/govuk_design_system_formbuilder/elements/date.rb#L75) thus the fallback to `attribute.try(:[], MULTIPARAMETER_KEY[segment])` is never attempted after `attribute.try(segment)`.
```
> attribute
> #<struct  day="", month="", year="">
```
In the specs however since the values are `nil`, `attribute.try(segment)` seems to fallback to `attribute.try(:[], MULTIPARAMETER_KEY[segment])`, throwing the index error

```
> attribute
> #<struct  day=nil, month=nil, year=nil>
```

**Comment by peteryates** [comment]
Thanks for reporting, I'll take a closer look now.

**Comment by peteryates** [comment]
Looking at your app it appears that you have some unnecessary complexity around the way you're handling dates. The formbuilder builds date inputs using the same param format as Rails' [date_select](https://api.rubyonrails.org/v6.1.0/classes/ActionView/Helpers/DateHelper.html#method-i-date_select) helper, meaning that when permitting the params in the controller you should only need to do something like this and Rails will know how to construct a date from the provided integers:

```patch
       def personal_details_params
         strip_whitespace(
           params.require(:candidate_interface_personal_details_form).permit(
-            :first_name, :last_name,
-            :"date_of_birth(3i)", :"date_of_birth(2i)", :"date_of_birth(1i)"
-          ).transform_keys { |key| dob_field_to_attribute(key) },
+            :first_name, :last_name, :date_of_birth
+          ),
         )
       end
```

It also allows you to remove lots of the setup logic and, when there's no date, simply provide a `nil`. I had a quick dive into it and [here's my progress](https://gist.github.com/peteryates/7d63f02ad120141e0aa535b44ea87a61) on simplifying it, if that's a route you want to explore.

Still, this highlights a weakness in this library's documentation and something that should be made more-apparent, probably via the docs and the guide. I noticed that [at least one other project](https://github.com/DFE-Digital/register-trainee-teachers/pull/735) had a similar failure so it might be worth us just supporting this behaviour anyway. Thoughts @cpjmcquillan?

**Comment by peteryates** [comment]
A quick update on this, we'll get a new release out in the next day or two that maintains the old behaviour of not failing with arguments it a format it's not expecting.

**Comment by cwrw** [comment]
Thanks for looking into this and for your prompt response @peteryates! I raised the date complexity you highlighted to the team today and we're going to look into simplifying the logic and if possible moving fully towards Rails standard date inputs.

The release is also welcome until we get to cleanup the code otherwise.
