### ISSUE TITLE
Date fields without day field

### ISSUE THREAD

**Issue by tvararu** [DFE-Digital/govuk_design_system_formbuilder#56]
Hello! Our service has date fields that look like this:

![Screenshot 2019-10-30 at 11 28 43](https://user-images.githubusercontent.com/1650875/67854562-743d5f00-fb08-11e9-8ff0-c4f71586b7f6.png)

It would be nice if the [date field component](https://govuk-form-builder.netlify.com/form-elements/date-field/) allowed this pattern.

Currently we still use it but we hide the day field using `display: none` in CSS. This has the downside of breaking the link from the error summary (because it points to the day field).

**Comment by peteryates** [comment]
This should be pretty straightforward to add with an additional param `include_day` that skips day and adds `link_errors` to the month input instead ([see here](https://github.com/DFE-Digital/govuk_design_system_formbuilder/blob/master/lib/govuk_design_system_formbuilder/elements/date.rb#L24)).
