### ISSUE TITLE
Support for setting labels, hints and legends via Rails' i18n

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/govuk_design_system_formbuilder#68]
Currently all of the helpers require that the text that's passed in to form labels, hints and legends is supplied inline. Many projects prefer to store the text in the locales files and use Rails' i18n to populate the relevant strings.

There's a working implementation in the [GOV.UK elements form builder](https://github.com/DFE-Digital/govuk_elements_form_builder/blob/master/lib/govuk_elements_form_builder/form_builder.rb#L604) that can be used for inspiration.

* [x] investigate the best approach for generically retrieving localisation values from Rails' store
* [x] ensure that strings are chosen in the correct preference order:
    1. provided
    2. localised
    3. automatic
* [x] work out the best structure to store hints and legends in the locales file
* [x] document the process in the guide

### Additional things to check

* [x] Should there be translations added for radio buttons and check boxes labels and hints? This _might_ be nice addition and could definitely be useful, but there's already `text_method:` and `:hint_method` which _probably_ already do everything that's required 🤔
* [x] ~~Should there be a shorthand way to specify to the helper which localisation key to use? Rather than doing something like `label: { text: I18n.t('my.favourite.type.of.pasta') }` perhaps `label: { t: 'my.favourite.type.of.pasta' }`? 🤷🏽‍♂️~~

**Comment by leeky** [comment]
This is a great addition!

Are there plans to make the i18n scopes configurable? For example, I'd like to use the ActiveRecord `activerecord.attributes.(model).(attribute_name)` scope for labels, because this would make the form labels and validations use the same text.

**Comment by peteryates** [comment]
Thank you!

I'm in agreement regarding being able to configure it, and generally being able to configure how the builder works is definitely on my radar (mainly for things like setting default label/legend sizes and tags, etc).

The automatic building of the path [is very straightforward](https://github.com/DFE-Digital/govuk_design_system_formbuilder/blob/ecbfc40682d469f9dcbf7ab7bd59e063fadad4ba/lib/govuk_design_system_formbuilder/base.rb#L99) and should be easily-overridable, but I think individually configuring the structure labels, hints and legends might get a bit complicated.

**Comment by peteryates** [comment]
This is now in the 1.1.0 branch
