### ISSUE TITLE
Enable use for plain ruby objects

### ISSUE THREAD

**Issue by jsugarman** [DFE-Digital/govuk_design_system_formbuilder#88]
Hi @peteryates, this is great stuff and was looking to implement in a product I am working on over in MoJ. 

One problem is you cannot use it against a plain ruby class due to the lack of `errors` on the object. I am just looking to create a basic search form with options.

I could monkey patch this or create a dummy `errors` method to patch this app-side but think it could be beneficial generally. I have a branch that I have it working in (with tests) but cannot push it - receive a `403`.

**Comment by peteryates** [comment]
Thanks Joel. I agree that adding the functionality to the gem is _probably_ a good idea - I can't see any reason not to! If you [fork this repo and create a PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) I'll gladly review your changes and collaborate on adding the feature.

**Comment by peteryates** [comment]
I had a _quick_ attempt @jsugarman, will this (#90) work for you?
