### ISSUE TITLE
Bump 1.1.1 to 1.2.0?

### ISSUE THREAD

**Issue by jsugarman** [DFE-Digital/govuk_design_system_formbuilder#94]
Hi @peteryates, 

Following on from the merge of the [govuk_password_field](https://github.com/DFE-Digital/govuk_design_system_formbuilder/commit/d8a70714a71e9f42a9ace82eed4badbfd4089886) I was just wondering if you were intending to bump the gem. Minor version seems appropriate.

regards

**Comment by peteryates** [comment]
Yep, will do tomorrow 👍

**Comment by peteryates** [comment]
I bumped it to `1.1.2` as the current functionality wasn't changed, only added to. Thanks for the PRs 👍
